### ISSUE TITLE
Cannot update environment variable on netlify site during build time

### ISSUE THREAD

**Issue by palinko91** [verygoodsecurity/netlify-plugin-vgs#9]
`❯ Loading plugins
   - @vgs/netlify-plugin-vgs@0.0.6 from Netlify app and package.json
​
@vgs/netlify-plugin-vgs (onPreBuild event)
────────────────────────────────────────────────────────────────
​
[vgs-plugin] onPreBuild, vaultId: xxx
[vgs-plugin] collectRouteExists: true
[vgs-plugin] netlify updateSite
[vgs-plugin] adding env variable VGS_ROUTE_ID xxx
[vgs-plugin] netlify updateSite error: TextHTTPError: Bad Request
    at parseJsonResponse (file:///C:/Users/arpad/OneDrive/Asztali%20g%C3%A9p/react/predictor_web_ui/node_modules/netlify/src/methods/response.js:37:35)
    at parseResponse (file:///C:/Users/arpad/OneDrive/Asztali%20g%C3%A9p/react/predictor_web_ui/node_modules/netlify/src/methods/response.js:9:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async callMethod (file:///C:/Users/arpad/OneDrive/Asztali%20g%C3%A9p/react/predictor_web_ui/node_modules/netlify/src/methods/index.js:31:26)
    at async onPreBuild (file:///C:/Users/arpad/OneDrive/Asztali%20g%C3%A9p/react/predictor_web_ui/node_modules/@vgs/netlify-plugin-vgs/index.js:30:7)
    at async Object.run (file:///C:/.npm-global/node_modules/netlify-cli/node_modules/@netlify/build/lib/plugins/child/run.js:14:5)
    at async handleEvent (file:///C:/.npm-global/node_modules/netlify-cli/node_modules/@netlify/build/lib/plugins/child/main.js:28:42)
    at async process.<anonymous> (file:///C:/.npm-global/node_modules/netlify-cli/node_modules/@netlify/build/lib/plugins/ipc.js:91:24) {
  status: 400,
  data: 'Site using new environment variables experience. Cannot update environment variables via Sites API. See https://open-api.netlify.com/#tag/environmentVariables'
}
[vgs-plugin] netlify updateSite finished!
​
(@vgs/netlify-plugin-vgs onPreBuild completed in 3.7s)`

**Comment by palinko91** [comment]
I've tried to fix it but unfortunatelly not that easy to get the account_id, some DNS setting endpoints returning it but returned me [] most likely cause I don't have other than default settings for now. I hope someone would have some idea how to find the **account_id** and complete the script:

`import { updateRoute, applyCollectRoute, tokenizationCollectRouteTemplate } from './routes.js';
import { getRouteConfig } from './utils.js';
import { NetlifyAPI } from 'netlify';

export const { VGS_VAULT_ID } = process.env;

export default {
  onPreBuild: async ({ constants }) => {
    console.log("[vgs-plugin] onPreBuild, vaultId:", VGS_VAULT_ID);

    const { NETLIFY_API_TOKEN } = constants;
    const netlify = new NetlifyAPI(NETLIFY_API_TOKEN);

    const routeConfig = getRouteConfig();

    if (routeConfig) {
      console.log('[vgs-plugin] starting route update')
      await updateRoute(VGS_VAULT_ID, routeConfig);

      console.log('[vgs-plugin] route update finished!')
    }

    const collectRoute = await applyCollectRoute(VGS_VAULT_ID);

    console.log('[vgs-plugin] netlify updateSite')
    try {
      console.log('[vgs-plugin] adding env variable VGS_ROUTE_ID', collectRoute.id)

      await netlify.setEnvVarValue(
        {
          account_id: /*todo(account_id) */,
          key: "VGS_ROUTE_ID",
          body: {
            context: "all",
            value: collectRoute.id
          }
        });
    } catch (e) {
      console.log('[vgs-plugin] netlify updateSite error:', e)
    }

    console.log('[vgs-plugin] netlify updateSite finished!')
  },
}
`

[https://open-api.netlify.com/#tag/environmentVariables/operation/setEnvVarValue](url)

Also it would be good if we could set query parameters for site_id, but the netlify library seems like not supporting right now.
